name: Validate Aws Credentials
on: 
  workflow_dispatch: {}
  
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentails@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}  
        
    - name: 
      run: aws s3 ls 
  
